import type { Escrow } from "../types";

export const escrowsData: Escrow[] = [
  // 🟡 Pending (Active)
  {
    id: "E-101",
    title: "Design Sprint Phase 1",
    from: "@0xAlfa",
    to: "@0xBeta",
    token: "USDC",
    amount: 1200,
    status: "pending",
    deadline: "2025-11-11",
    type: "public",
    description: "Design sprint including UX flows and wireframes.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "E-102",
    title: "Frontend Development",
    from: "@0xLuna",
    to: "@0xNova",
    token: "ETH",
    amount: 1,
    status: "pending",
    deadline: "2025-12-01",
    type: "public",
    description: "Landing page and dashboard components.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "E-103",
    title: "DAO Graphic Assets",
    from: "@0xEcho",
    to: "@0xAlfa",
    token: "DAI",
    amount: 500,
    status: "pending",
    deadline: "2025-12-15",
    type: "public",
    description: "Graphics for social media and proposals.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },

  // 🟢 Completed
  {
    id: "E-099",
    title: "Audit Settlement",
    from: "@0xAstra",
    to: "@0xNova",
    token: "ETH",
    amount: 0.5,
    status: "completed",
    deadline: "2025-09-01",
    type: "public",
    description: "Security audit settlement for v1 contracts.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 18,
  },
  {
    id: "E-098",
    title: "Content Bounty",
    from: "@0xWriter",
    to: "@0xAlfa",
    token: "USDC",
    amount: 300,
    status: "completed",
    deadline: "2025-09-20",
    type: "public",
    description: "Technical blog post about smart contracts.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 25,
  },
  {
    id: "E-097A",
    title: "Brand Kit Delivery",
    from: "@0xEcho",
    to: "@0xVega",
    token: "DAI",
    amount: 700,
    status: "completed",
    deadline: "2025-09-30",
    type: "public",
    description: "Finalized logos and brand assets.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 20,
  },

  // 🔴 Disputed (Frozen)
  {
    id: "E-097",
    title: "Marketing Retainer",
    from: "@0xOrion",
    to: "@0xEcho",
    token: "DAI",
    amount: 800,
    status: "frozen",
    deadline: "2025-10-12",
    type: "public",
    description: "Monthly retainer. Disputed deliverables.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 8,
  },
  {
    id: "E-096",
    title: "Bug Fix Bounty",
    from: "@0xBuggy",
    to: "@0xCoder",
    token: "USDC",
    amount: 150,
    status: "frozen",
    deadline: "2025-10-20",
    type: "public",
    description: "Disagreement on issue reproduction.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
  },
  {
    id: "E-095",
    title: "Private NDA",
    from: "@you",
    to: "@partner",
    token: "USDC",
    amount: 200,
    status: "pending",
    deadline: "2025-12-22",
    type: "private",
    description: "Private NDA with milestone clause.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: "E-110",
    title: "Web3 Copywriting",
    from: "@0xPen",
    to: "@0xInk",
    token: "USDC",
    amount: 250,
    status: "signed",
    deadline: "2025-12-10",
    type: "public",
    description: "Ongoing copywriting engagement for Web3 DAO.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 6,
  },
  {
    id: "E-111",
    title: "Abandoned Translation Deal",
    from: "@0xEcho",
    to: "@0xBeta",
    token: "DAI",
    amount: 300,
    status: "cancelled",
    deadline: "2025-10-05",
    type: "public",
    description: "Cancelled translation project due to inactivity.",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
  },
];
