export const ReputationEventTypeEnum = {
  TelegramVerified: 1,
  AgreementCompleted: 2,
  AgreementEscrowCompleted: 3,
  DisputeWon: 4,
  VotedWinningOutcome: 5,
  WitnessEvery5Comments: 6,
  JudgeWinningVote: 7,
  JudgeCommentAdded: 8,
  FirstJudgeToVote: 9,
  FirstCommunityToVote: 10,
  CommunityVoteLost: 50,
  JudgeVoteLost: 51,
  DisputeLostRegular: 52,
  DisputeLostEscrow: 53,
  LateDelivery: 54,
  FrequentCancellationsBanned: 55,
  SpamAgreementsTempBan: 56,
} as const;
