export type RawAgreementArray = [
    _id?: bigint | number | string,
    creator?: string,
    serviceProvider?: string,
    serviceRecipient?: string,
    token?: string,
    amount?: bigint | number | string,
    remainingAmount?: bigint | number | string,
    createdAt?: bigint | number | string,
    deadline?: bigint | number | string,
    deadlineDuration?: bigint | number | string,
    grace1Ends?: bigint | number | string,
    grace2Ends?: bigint | number | string,
    grace1EndsCalledBy?: string,
    grace2EndsCalledBy?: string,
    funded?: boolean | number,
    signed?: boolean | number,
    acceptedByServiceProvider?: boolean | number,
    acceptedByServiceRecipient?: boolean | number,
    completed?: boolean | number,
    disputed?: boolean | number,
    privateMode?: boolean | number,
    frozen?: boolean | number,
    pendingCancellation?: boolean | number,
    orderCancelled?: boolean | number,
    vesting?: boolean | number,
    deliverySubmited?: boolean | number,
    votingId?: bigint | number | string,
];